/** Handles alternate recipes for brewery and vinery that make brewing and winemaking easier to automate */

ServerEvents.recipes(event => {
    event.shaped('gtceu:fermentation_barrel', [
        'BAB',
        'DCD',
        'BAB',
    ],
    {
        A: 'gtceu:clean_machine_casing',
        B: 'gtceu:treated_wood_frame',
        C: 'gtceu:stainless_steel_rotor',
        D: '#gtceu:circuits/hv'

    }).id('kubejs:fermentation_barrel_controller')
    // Vinery
    // Raw juices
    event.recipes.gtceu.forming_press('kubejs:red_grapejuice')
        .itemInputs('2x vinery:red_grape', 'vinery:wine_bottle')
        .itemOutputs('vinery:red_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:white_grapejuice')
        .itemInputs('2x vinery:white_grape', 'vinery:wine_bottle')
        .itemOutputs('vinery:white_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:red_taiga_grapejuice')
        .itemInputs('2x vinery:taiga_grapes_red', 'vinery:wine_bottle')
        .itemOutputs('vinery:red_taiga_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:white_taiga_grapejuice')
        .itemInputs('2x vinery:taiga_grapes_white', 'vinery:wine_bottle')
        .itemOutputs('vinery:white_taiga_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:red_jungle_grapejuice')
        .itemInputs('2x vinery:jungle_grapes_red', 'vinery:wine_bottle')
        .itemOutputs('vinery:red_jungle_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:white_jungle_grapejuice')
        .itemInputs('2x vinery:jungle_grapes_white', 'vinery:wine_bottle')
        .itemOutputs('vinery:white_jungle_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:red_savanna_grapejuice')
        .itemInputs('2x vinery:savanna_grapes_red', 'vinery:wine_bottle')
        .itemOutputs('vinery:red_savanna_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:white_savanna_grapejuice')
        .itemInputs('2x vinery:savanna_grapes_white', 'vinery:wine_bottle')
        .itemOutputs('vinery:white_savanna_grapejuice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:apple_mash')
        .itemInputs('2x minecraft:apple')
        .itemOutputs('vinery:apple_mash')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.forming_press('kubejs:apple_juice')
        .itemInputs('vinery:apple_mash', 'vinery:wine_bottle')
        .itemOutputs('vinery:apple_juice')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    // Actual wines
    event.recipes.gtceu.fermentation_barrel('kubejs:mead')
        .itemInputs('minecraft:honey_bottle', 'minecraft:sugar', 'vinery:wine_bottle')
        .itemOutputs('vinery:mead')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:apple_cider')
        .itemInputs('vinery:apple_mash', 'minecraft:sugar', 'vinery:wine_bottle')
        .itemOutputs('vinery:apple_cider')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:apple_wine')
        .itemInputs('vinery:apple_juice', 'vinery:wine_bottle')
        .itemOutputs('vinery:apple_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:mellohi_wine')
        .itemInputs('minecraft:glowstone_dust', 'minecraft:sugar', '#vinery:white_grapejuice')
        .itemOutputs('vinery:mellohi_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:glowing_wine')
        .itemInputs('minecraft:glow_berries', '#vinery:white_grapejuice')
        .itemOutputs('vinery:glowing_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:solaris_wine')
        .itemInputs('minecraft:sweet_berries', 'minecraft:honey_bottle', '#vinery:white_grapejuice')
        .itemOutputs('vinery:solaris_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:noir_wine')
        .itemInputs('minecraft:sweet_berries', '#vinery:red_grapejuice')
        .itemOutputs('vinery:noir_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:red_wine')
        .itemInputs('minecraft:sugar', '#vinery:red_grapejuice')
        .itemOutputs('vinery:red_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:strad_wine')
        .itemInputs('minecraft:cocoa_beans', '#forge:dusts/wood', '#vinery:red_grapejuice')
        .itemOutputs('vinery:strad_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:cherry_wine')
        .itemInputs('vinery:cherry', '#vinery:white_grapejuice')
        .itemOutputs('vinery:cherry_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:cristel_wine')
        .itemInputs('minecraft:feather', 'minecraft:blaze_rod', 'vinery:white_jungle_grapejuice')
        .itemOutputs('vinery:cristel_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:creepers_crush')
        .itemInputs('#forge:dusts/saltpeter','minecraft:gunpowder', '#vinery:white_grapejuice')
        .itemOutputs('vinery:creepers_crush')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:kelp_cider')
        .itemInputs('minecraft:kelp', 'vinery:wine_bottle')
        .itemOutputs('vinery:kelp_cider')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:lilitu_wine')
        .itemInputs('vinery:cherry', 'minecraft:honey_bottle', 'vinery:red_taiga_grapejuice')
        .itemOutputs('vinery:lilitu_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:jo_special_mixture')
        .itemInputs('minecraft:fermented_spider_eye', 'minecraft:string', 'vinery:white_savanna_grapejuice')
        .itemOutputs('vinery:jo_special_mixture')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:eiswein')
        .itemInputs('minecraft:snowball', '#forge:dusts/ice', 'vinery:white_taiga_grapejuice')
        .itemOutputs('vinery:eiswein')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:aegis_wine')
        .itemInputs('minecraft:sugar', '#forge:ingots/iron', 'vinery:kelp_cider')
        .itemOutputs('vinery:aegis_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:bolvar_wine')
        .itemInputs('minecraft:honeycomb', 'vinery:cherry', 'vinery:white_grapejuice')
        .itemOutputs('vinery:bolvar_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:chorus_wine')
        .itemInputs('minecraft:chorus_fruit', '#forge:dusts/ender_pearl', 'vinery:wine_bottle')
        .itemOutputs('vinery:chorus_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:villagers_fright')
        .itemInputs('minecraft:arrow', '#forge:dusts/emerald', '#vinery:grapejuice')
        .itemOutputs('vinery:villagers_fright')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:clark_wine')
        .itemInputs('minecraft:rabbit_foot', '#forge:dusts/gold', 'vinery:white_savanna_grapejuice')
        .itemOutputs('vinery:clark_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:magnetic_wine')
        .itemInputs('#forge:ingots/magnetic_iron', 'vinery:cherry_wine')
        .itemOutputs('vinery:magnetic_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:stal_wine')
        .itemInputs('#forge:dusts/carbon', '#forge:dusts/realgar', 'vinery:strad_wine')
        .itemOutputs('vinery:stal_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:chenet_wine')
        .itemInputs('minecraft:spider_eye', 'minecraft:cobweb', 'vinery:red_savanna_grapejuice')
        .itemOutputs('vinery:chenet_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:bottle_mojang_noir')
        .itemInputs('minecraft:golden_apple', 'vinery:red_wine', 'vinery:noir_wine')
        .itemOutputs('vinery:bottle_mojang_noir')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:jellie_wine')
        .itemInputs('vinery:apple_wine', 'vinery:chenet_wine', 'vinery:bolvar_wine')
        .itemOutputs('vinery:jellie_wine')
        .duration(12000)
        .EUt(GTValues.VA[GTValues.MV])

    // Brewery
    event.recipes.gtceu.fermentation_barrel('kubejs:wheat_beer')
        .itemInputs('brewery:dried_wheat', 'brewery:hops', 'farm_and_charm:yeast')
        .itemOutputs('brewery:beer_wheat')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:barley_beer')
        .itemInputs('brewery:dried_barley', 'brewery:hops', 'farm_and_charm:yeast')
        .itemOutputs('brewery:beer_barley')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:hops_beer')
        .itemInputs('brewery:hops_seeds', 'brewery:hops', 'farm_and_charm:yeast')
        .itemOutputs('brewery:beer_hops')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:nettle_beer')
        .itemInputs('farm_and_charm:wild_nettle', 'brewery:hops', 'farm_and_charm:yeast')
        .itemOutputs('brewery:beer_nettle')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:oat_beer')
        .itemInputs('brewery:dried_oat', 'brewery:hops', 'farm_and_charm:yeast')
        .itemOutputs('brewery:beer_oat')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:haley_beer')
        .itemInputs('minecraft:popped_chorus_fruit', 'brewery:hops', 'farm_and_charm:yeast')
        .itemOutputs('brewery:beer_haley')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_jojannik')
        .itemInputs('farm_and_charm:barley', 'brewery:dried_barley', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_jojannik')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_lilitusinglemalt')
        .itemInputs('brewery:dried_wheat', 'brewery:dried_barley', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_lilitusinglemalt')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_cristelwalker')
        .itemInputs('farm_and_charm:corn', 'brewery:dried_corn', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_cristelwalker')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_maggoallan')
        .itemInputs('minecraft:wheat', 'brewery:dried_wheat', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_maggoallan')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_carrasconlabel')
        .itemInputs('brewery:dried_wheat', 'brewery:dried_corn', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_carrasconlabel')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_ak')
        .itemInputs('brewery:dried_oat', 'brewery:dried_corn', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_ak')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_highland_hearth')
        .itemInputs('brewery:dried_wheat', 'brewery:dried_oat', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_highland_hearth')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_smokey_reverie')
        .itemInputs('farm_and_charm:oat', 'brewery:dried_oat', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_smokey_reverie')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.fermentation_barrel('kubejs:whiskey_jamesons_malt')
        .itemInputs('brewery:dried_barley', 'brewery:dried_wheat', 'farm_and_charm:yeast')
        .itemOutputs('brewery:whiskey_jamesons_malt')
        .duration(6000)
        .EUt(GTValues.VA[GTValues.MV])

    // Grain drying recipes for solar grain drier
    event.recipes.gtceu.solar_grain_drier('kubejs:dried_wheat')
        .itemInputs('4x minecraft:wheat')
        .itemOutputs('4x brewery:dried_wheat')
        .duration(160)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:dried_barley')
        .itemInputs('4x farm_and_charm:barley')
        .itemOutputs('4x brewery:dried_barley')
        .duration(160)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:dried_corn')
        .itemInputs('4x farm_and_charm:corn')
        .itemOutputs('4x brewery:dried_corn')
        .duration(160)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:dried_oat')
        .itemInputs('4x farm_and_charm:oat')
        .itemOutputs('4x brewery:dried_oat')
        .duration(160)
        .EUt(GTValues.VA[GTValues.LV])
    // Bone meal drying recipes
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_barley_bone_meal')
        .itemInputs('4x farm_and_charm:wild_barley')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_corn_bone_meal')
        .itemInputs('4x farm_and_charm:wild_corn')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_carrot_bone_meal')
        .itemInputs('4x farm_and_charm:wild_carrots')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_tomato_bone_meal')
        .itemInputs('4x farm_and_charm:wild_tomatoes')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_emmer_bone_meal')
        .itemInputs('4x farm_and_charm:wild_emmer')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_lettuce_bone_meal')
        .itemInputs('4x farm_and_charm:wild_lettuce')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_strawberry_bone_meal')
        .itemInputs('4x farm_and_charm:wild_strawberries')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_oat_bone_meal')
        .itemInputs('4x farm_and_charm:wild_oat')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_potato_bone_meal')
        .itemInputs('4x farm_and_charm:wild_potatoes')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_beetroot_bone_meal')
        .itemInputs('4x farm_and_charm:wild_beetroots')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_ribwort_bone_meal')
        .itemInputs('4x farm_and_charm:wild_ribwort')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:wild_onion_bone_meal')
        .itemInputs('4x farm_and_charm:wild_onions')
        .itemOutputs('4x minecraft:bone_meal')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])
    // Misc drying recipes
    event.recipes.gtceu.solar_grain_drier('kubejs:fertilized_soil')
        .itemInputs('4x minecraft:podzol')
        .itemOutputs('4x farm_and_charm:fertilized_soil')
        .duration(640)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:bone_meal_fertilizer')
        .itemInputs('4x minecraft:bone_meal')
        .itemOutputs('4x farm_and_charm:fertilizer')
        .duration(640)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.solar_grain_drier('kubejs:rotten_flesh_fertilizer')
        .itemInputs('4x minecraft:rotten_flesh')
        .itemOutputs('4x farm_and_charm:fertilizer')
        .duration(640)
        .EUt(GTValues.VA[GTValues.LV])
    // Recipe for the drier controller itself
    event.shaped('gtceu:solar_grain_drier', [
        'ABA',
        'DCD',
        'ABA',
    ],
    {
        A: 'gtceu:heatproof_machine_casing',
        B: 'gtceu:treated_wood_frame',
        C: 'create:blaze_burner',
        D: '#gtceu:circuits/mv'
    }).id('kubejs:solar_grain_drier_controller')
})