
#Settings for the mechanical chicken
[create_mechanical_chicken]
	#Processing time (in ticks)
	#Range: > 0
	processingTime = 500
	#Stress impact
	#Range: 0.0 ~ 64.0
	stressImpact = 4.0
	#Fluid capacity
	#Range: > 1
	fluidCapacity = 1000
	#Required fluid amount
	#Range: > 0
	requiredFluidAmount = 100
	#Output amount
	#Range: > 1
	outputAmount = 1
	#Required fluid
	requiredFluid = "gtceu:seed_oil"
	seedOilEnabled = false

