/** Advanced Culinary Array recipes - both crafting and to craft it*/
ServerEvents.recipes(event => {
    // Array controller
    event.shaped('gtceu:advanced_culinary_array', [
        'DAD',
        'BCB',
        'EAE'
    ], {
        A: '#gtceu:circuits/luv',
        B: 'cookingforblockheads:cooking_table',
        C: 'gtceu:luv_mixer',
        D: 'cookingforblockheads:fridge',
        E: '#cookingforblockheads:ovens'
    })
    // Vanilla foods
    // Cake
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cake')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', '#forge:eggs')
        .itemOutputs('minecraft:cake')
        .inputFluids('minecraft:milk 288')
        .duration(480)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    // Pumpkin pie
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pumpkin_pie')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', '#forge:eggs', 'minecraft:pumpkin')
        .itemOutputs('3x minecraft:pumpkin_pie')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Cookies
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cookies')
        .itemInputs('2x #forge:grain')
        .inputFluids('create:chocolate 125')
        .itemOutputs('16x minecraft:cookie')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    // Mushroom stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_mushroom_stew')
        .itemInputs('2x #forge:mushrooms')
        .itemOutputs('2x minecraft:mushroom_stew')
        .inputFluids('minecraft:water 250')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Beetroot soup
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_beetroot_soup')
        .itemInputs('2x minecraft:beetroot')
        .itemOutputs('2x minecraft:beetroot_soup')
        .inputFluids('minecraft:water 250')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Rabbit stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_rabbit_stew')
        .itemInputs('minecraft:rabbit', '2x #forge:vegetables', '#forge:mushrooms', 'minecraft:potato')
        .itemOutputs('2x minecraft:rabbit_stew')
        .inputFluids('minecraft:water 250')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Farmer's Delight foods
    // Cake slice
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cake_slice')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', '#forge:eggs')
        .itemOutputs('8x farmersdelight:cake_slice')
        .inputFluids('minecraft:milk 288')
        .duration(600)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    // Apple pie
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_apple_pie')
        .itemInputs('4x #forge:grain', '2x #forge:dusts/sugar', '3x minecraft:apple')
        .itemOutputs('2x farmersdelight:apple_pie')
        .inputFluids('minecraft:milk 250')
        .duration(480)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    // Apple pie slice
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_apple_pie_slice')
        .itemInputs('4x #forge:grain', '2x #forge:dusts/sugar', '3x minecraft:apple')
        .itemOutputs('8x farmersdelight:apple_pie_slice')
        .inputFluids('minecraft:milk 250')
        .duration(600)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    // Sweet berry cheesecake
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_sweet_berry_cheesecake')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', '4x minecraft:sweet_berries')
        .itemOutputs('2x farmersdelight:sweet_berry_cheesecake')
        .inputFluids('minecraft:milk 500')
        .circuit(1)
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Sweet berry cheesecake slice
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_sweet_berry_cheesecake_slice')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', '4x minecraft:sweet_berries')
        .itemOutputs('8x farmersdelight:sweet_berry_cheesecake_slice')
        .inputFluids('minecraft:milk 500')
        .duration(600)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    // Chocolate pie
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chocolate_pie')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', 'minecraft:cocoa_beans')
        .itemOutputs('2x farmersdelight:chocolate_pie')
        .inputFluids('minecraft:milk 500', 'create:chocolate 500')
        .duration(480)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    // Chocolate pie slice
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chocolate_pie_slice')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', 'minecraft:cocoa_beans')
        .itemOutputs('8x farmersdelight:chocolate_pie_slice')
        .inputFluids('minecraft:milk 500', 'create:chocolate 500')
        .duration(600)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    // Sweet berry cookie
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_sweet_berry_cookie')
        .itemInputs('2x #forge:grain', '#forge:dusts/sugar', 'minecraft:sweet_berries')
        .itemOutputs('16x farmersdelight:sweet_berry_cookie')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    // Honey cookie
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_honey_cookie')
        .itemInputs('2x #forge:grain')
        .itemOutputs('16x farmersdelight:honey_cookie')
        .inputFluids('create:honey 250')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    // Melon popsicle
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_melon_popsicle')
        .itemInputs('2x #forge:dusts/ice', '3x minecraft:melon_slice')
        .itemOutputs('3x farmersdelight:melon_popsicle')
        .inputFluids('minecraft:water 500')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Glow berry custard
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_glow_berry_custard')
        .itemInputs('2x minecraft:glow_berries', '#forge:dusts/sugar', '#forge:eggs')
        .itemOutputs('3x farmersdelight:glow_berry_custard')
        .inputFluids('minecraft:milk 250')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Fruit salad
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fruit_salad')
        .itemInputs('2x #forge:berries', 'minecraft:apple', '2x minecraft:melon_slice')
        .itemOutputs('2x farmersdelight:fruit_salad')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Mixed salad
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_mixed_salad')
        .itemInputs('3x #forge:vegetables', '#forge:crops/cabbage')
        .itemOutputs('2x farmersdelight:mixed_salad')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    // Nether salad
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_nether_salad')
        .itemInputs('minecraft:crimson_fungus', 'minecraft:warped_fungus')
        .itemOutputs('2x farmersdelight:nether_salad')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    // Barbecue on a stick
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_barbecue_stick')
        .itemInputs('#forge:foods/meat/cooked', '2x #forge:vegetables', '#forge:dusts/charcoal')
        .itemOutputs('4x farmersdelight:barbecue_stick')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Egg sandwich
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_egg_sandwich')
        .itemInputs('3x #forge:grain', '2x #forge:eggs')
        .itemOutputs('2x farmersdelight:egg_sandwich')
        .duration(560)
        .EUt(GTValues.VA[GTValues.EV])
    // Chicken sandwich
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chicken_sandwich')
        .itemInputs('3x #forge:grain', '#forge:raw_chicken', "#forge:crops/cabbage", "minecraft:carrot")
        .itemOutputs('2x farmersdelight:chicken_sandwich')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Hamburger
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_hamburger')
        .itemInputs('3x #forge:grain', '#forge:raw_beef', '#forge:crops/cabbage', "2x #forge:vegetables")
        .itemOutputs('2x farmersdelight:hamburger')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Bacon sandwich
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_bacon_sandwich')
        .itemInputs('3x #forge:grain', '#forge:raw_pork', '#forge:crops/cabbage', "#forge:vegetables")
        .itemOutputs('2x farmersdelight:bacon_sandwich')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Mutton wrap
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_mutton_wrap')
        .itemInputs('3x #forge:grain', '#forge:raw_mutton', '#forge:crops/cabbage', "#forge:vegetables")
        .itemOutputs('2x farmersdelight:mutton_wrap')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Dumplings
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dumplings')
        .itemInputs('4x #forge:grain', '#farmersdelight:cabbage_roll_ingredients', '#forge:crops/cabbage', "#forge:vegetables")
        .itemOutputs('3x farmersdelight:dumplings')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Stuffed potato
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_potato')
        .itemInputs('#forge:raw_beef', '3x minecraft:potato')
        .itemOutputs('3x farmersdelight:stuffed_potato')
        .inputFluids('minecraft:milk 250')
        .duration(560)
        .EUt(GTValues.VA[GTValues.EV])
    // Cabbage rolls
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cabbage_rolls')
        .itemInputs('#forge:crops/cabbage', '#farmersdelight:cabbage_roll_ingredients')
        .itemOutputs('2x farmersdelight:cabbage_rolls')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    // Salmon roll
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_salmon_roll')
        .itemInputs('#forge:raw_fishes/salmon', '#forge:crops/rice')
        .itemOutputs('2x farmersdelight:salmon_roll')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Cod roll
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cod_roll')
        .itemInputs('#forge:raw_fishes/cod', '#forge:crops/rice')
        .itemOutputs('2x farmersdelight:cod_roll')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Kelp roll
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_kelp_roll')
        .itemInputs('2x #forge:crops/rice', '2x minecraft:dried_kelp', 'minecraft:carrot')
        .itemOutputs('3x farmersdelight:kelp_roll')
        .duration(240)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    // Kelp roll slice (basically sushi)
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_kelp_roll_slice')
        .itemInputs('2x #forge:crops/rice', '2x minecraft:dried_kelp', 'minecraft:carrot')
        .itemOutputs('9x farmersdelight:kelp_roll_slice')
        .duration(320)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    // Beef stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_beef_stew')
        .itemInputs('#forge:raw_beef', '#forge:vegetables', 'minecraft:potato')
        .itemOutputs('2x farmersdelight:beef_stew')
        .inputFluids('minecraft:water 250')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Chicken soup
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chicken_soup')
        .itemInputs('#forge:raw_chicken', '#forge:vegetables', 'minecraft:potato', 'minecraft:carrot')
        .itemOutputs('2x farmersdelight:chicken_soup')
        .inputFluids('minecraft:water 250')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Vegetable soup
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_vegetable_soup')
        .itemInputs('3x #forge:vegetables', '#forge:crops/cabbage')
        .itemOutputs('2x farmersdelight:vegetable_soup')
        .inputFluids('minecraft:water 250')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Fish stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fish_stew')
        .itemInputs('#forge:raw_fishes', '2x #forge:crops/tomato', '#forge:crops/onion')
        .itemOutputs('2x farmersdelight:fish_stew')
        .inputFluids('minecraft:water 250')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Fried rice
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fried_rice')
        .itemInputs('#forge:crops/rice', '#forge:eggs', '2x #forge:vegetables')
        .itemOutputs('2x farmersdelight:fried_rice')
        .inputFluids('minecraft:water 250')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    // Pumpkin soup
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pumpkin_soup')
        .itemInputs('minecraft:pumpkin', '2x #forge:raw_pork', "2x #forge:crops/cabbage")
        .itemOutputs('4x farmersdelight:pumpkin_soup')
        .inputFluids('minecraft:milk 500')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Baked cod stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_baked_cod_stew')
        .itemInputs('#forge:raw_fishes/cod', '#forge:crops/tomato', 'minecraft:potato', '#forge:eggs')
        .itemOutputs('2x farmersdelight:baked_cod_stew')
        .inputFluids('minecraft:water 250')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Noodle soup
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_noodle_soup')
        .itemInputs('#forge:raw_pork', '3x #forge:grain', 'minecraft:dried_kelp', '#forge:eggs')
        .itemOutputs('2x farmersdelight:noodle_soup')
        .inputFluids('minecraft:water 250')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Bacon and eggs
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_bacon_and_eggs')
        .itemInputs('#forge:raw_pork', '#forge:eggs')
        .itemOutputs('2x farmersdelight:bacon_and_eggs')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    // Pasta with meatballs
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pasta_with_meatballs')
        .itemInputs('#forge:raw_beef', '3x #forge:grain', '2x #forge:crops/tomato')
        .itemOutputs('2x farmersdelight:pasta_with_meatballs')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Pasta with mutton chop
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pasta_with_mutton_chop')
        .itemInputs('#forge:raw_mutton', '3x #forge:grain', '2x #forge:crops/tomato')
        .itemOutputs('2x farmersdelight:pasta_with_mutton_chop')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Mushroom rice
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_mushroom_rice')
        .itemInputs('2x #forge:mushrooms', '#forge:crops/rice', '#forge:vegetables')
        .itemOutputs('2x farmersdelight:mushroom_rice')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Roasted mutton chops
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_roasted_mutton_chops')
        .itemInputs('#forge:raw_mutton', 'minecraft:beetroot', '#forge:crops/rice', '#forge:crops/tomato')
        .itemOutputs('2x farmersdelight:roasted_mutton_chops')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Vegetable noodles
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_vegetable_noodles')
        .itemInputs('3x #forge:vegetables', '3x #forge:grain', '#forge:mushrooms')
        .itemOutputs('2x farmersdelight:vegetable_noodles')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Steak and potatoes
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_steak_and_potatoes')
        .itemInputs('#forge:raw_beef', '#forge:crops/onion', '#forge:crops/rice', '2x minecraft:potato')
        .itemOutputs('2x farmersdelight:steak_and_potatoes')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Ratatouille
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_ratatouille')
        .itemInputs('2x #forge:vegetables', '#forge:crops/tomato', '#forge:crops/onion')
        .itemOutputs('2x farmersdelight:ratatouille')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    // Squid ink pasta
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_squid_ink_pasta')
        .itemInputs('#forge:raw_fishes', '3x #forge:grain', '#forge:crops/tomato', 'minecraft:ink_sac')
        .itemOutputs('2x farmersdelight:squid_ink_pasta')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Grilled salmon
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_grilled_salmon')
        .itemInputs('#forge:raw_fishes/salmon', '#forge:crops/cabbage', '#forge:crops/onion', 'minecraft:sweet_berries')
        .itemOutputs('2x farmersdelight:grilled_salmon')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Roast chicken (skip the block, make plates directly)
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_roast_chicken')
        .itemInputs('#forge:raw_chicken', '#forge:crops/onion', '2x #forge:grain', '2x #forge:vegetables', '#forge:eggs', '2x minecraft:potato')
        .itemOutputs('4x farmersdelight:roast_chicken', 'minecraft:bone_meal')
        .duration(1500)
        .EUt(GTValues.VA[GTValues.EV])
    // Stuffed pumpkin (skip the block, make bowls directly)
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_pumpkin')
        .itemInputs('minecraft:pumpkin', '#forge:crops/rice', '#forge:berries', '3x #forge:vegetables', '#forge:mushrooms')
        .itemOutputs('4x farmersdelight:stuffed_pumpkin')
        .duration(1200)
        .EUt(GTValues.VA[GTValues.EV])
    // Honey glazed ham (skip the block, make plates directly)
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_honey_glazed_ham')
        .itemInputs('farmersdelight:ham', '4x #forge:berries', '2x #forge:crops/rice')
        .itemOutputs('4x farmersdelight:honey_glazed_ham', 'minecraft:bone')
        .inputFluids('create:honey 250')
        .duration(1500)
        .EUt(GTValues.VA[GTValues.EV])
    // Shepherd's pie (skip the block, make plates directly)
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_shepherds_pie')
        .itemInputs('2x #forge:raw_mutton', '2x minecraft:potato', '2x #forge:grain', '2x #forge:crops/onion')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('4x farmersdelight:shepherds_pie')
        .duration(1500)
        .EUt(GTValues.VA[GTValues.EV])
    // Rice roll medley (block cannot be skipped. Combine ingredients of salmon rolls, cod rolls, and kelp roll slices)
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_rice_roll_medley')
        .itemInputs('3x #forge:raw_fishes', '4x #forge:crops/rice', '2x minecraft:dried_kelp', 'minecraft:carrot')
        .itemOutputs('farmersdelight:rice_roll_medley_block')
        .duration(1800)
        .EUt(GTValues.VA[GTValues.EV])
    // Dog food
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dog_food_fd')
        .itemInputs('#farmersdelight:wolf_prey', 'minecraft:bone_meal', 'minecraft:rotten_flesh', '#forge:crops/rice')
        .itemOutputs('2x farmersdelight:dog_food')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Horse feed
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_horse_feed')
        .itemInputs('#centaur:ed_bales', '2x minecraft:apple', 'minecraft:golden_carrot')
        .itemOutputs('2x farmersdelight:horse_feed')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Rustic delight foods
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_coffee')
        .itemInputs('4x #forge:seeds/coffee')
        .inputFluids('minecraft:water 250')
        .itemOutputs('3x rusticdelight:coffee')
        .circuit(1)
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_milk_coffee')
        .itemInputs('4x #forge:seeds/coffee')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('3x rusticdelight:milk_coffee')
        .circuit(1)
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chocolate_coffee')
        .itemInputs('4x #forge:seeds/coffee')
        .inputFluids('minecraft:milk 250', 'create:chocolate 125')
        .itemOutputs('3x rusticdelight:chocolate_coffee')
        .circuit(2)
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_honey_coffee')
        .itemInputs('4x #forge:seeds/coffee')
        .inputFluids('minecraft:milk 250', 'create:honey 125')
        .itemOutputs('3x rusticdelight:honey_coffee')
        .circuit(3)
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_syrup_coffee')
        .itemInputs('4x #forge:seeds/coffee', 'minecraft:apple', '#forge:dusts/sugar')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('3x rusticdelight:syrup_coffee')
        .circuit(4)
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dark_coffee')
        .itemInputs('7x #forge:seeds/coffee')
        .inputFluids('minecraft:water 250')
        .itemOutputs('3x rusticdelight:dark_coffee')
        .circuit(2)
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_syrup_cheesecake')
        .itemInputs('3x #forge:grain', '8x #forge:dusts/sugar', '4x minecraft:apple')
        .itemOutputs('2x rusticdelight:syrup_cheesecake')
        .inputFluids('minecraft:milk 500')
        .duration(480)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_syrup_cheesecake_slices')
        .itemInputs('3x #forge:grain', '8x #forge:dusts/sugar', '4x minecraft:apple')
        .itemOutputs('8x rusticdelight:syrup_cheesecake_slice')
        .inputFluids('minecraft:milk 500')
        .duration(600)
        .circuit(25)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cherry_blossom_cheesecake')
        .itemInputs('3x #forge:grain', '3x #forge:dusts/sugar', '4x #rusticdelight:cherry_blossom_ingredients')
        .itemOutputs('2x rusticdelight:cherry_blossom_cheesecake')
        .inputFluids('minecraft:milk 500')
        .duration(480)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cherry_blossom_cheesecake_slices')
        .itemInputs('3x #forge:grain', '3x #forge:dusts/sugar', '4x #rusticdelight:cherry_blossom_ingredients')
        .itemOutputs('8x rusticdelight:cherry_blossom_cheesecake_slice')
        .inputFluids('minecraft:milk 500')
        .duration(600)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_syrup_cookie')
        .itemInputs('3x #forge:grain', '#forge:dusts/sugar', 'minecraft:apple')
        .itemOutputs('16x rusticdelight:syrup_cookie')
        .duration(360)
        .circuit(6)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cherry_blossom_cookie')
        .itemInputs('3x #forge:grain', '2x #rusticdelight:cherry_blossom_ingredients')
        .itemOutputs('16x rusticdelight:cherry_blossom_cookie')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_coffee_cookie')
        .itemInputs('3x #forge:grain', '2x #forge:seeds/coffee')
        .itemOutputs('16x rusticdelight:coffee_cookie')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_syrup_sandwich')
        .itemInputs('2x #forge:grain', '2x #forge:dusts/sugar', 'minecraft:apple')
        .itemOutputs('2x rusticdelight:syrup_sandwich')
        .duration(600)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fruit_beignet')
        .itemInputs('4x #rusticdelight:cooking_oil_ingredients', '2x #forge:grain', "2x #forge:berries", "#forge:dusts/sugar")
        .itemOutputs('4x rusticdelight:fruit_beignet')
        .duration(750)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pancakes')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '4x #forge:dusts/sugar', 'minecraft:apple')
        .itemOutputs('2x rusticdelight:pancakes')
        .inputFluids('minecraft:milk 250')
        .circuit(1)
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pancakes_direct')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '4x #forge:dusts/sugar', 'minecraft:apple')
        .itemOutputs('12x rusticdelight:pancake')
        .inputFluids('minecraft:milk 250')
        .circuit(24)
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_honey_pancakes')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '2x #forge:dusts/sugar', 'minecraft:sweet_berries')
        .itemOutputs('2x rusticdelight:honey_pancakes')
        .inputFluids('minecraft:milk 250', 'create:honey 250')
        .circuit(1)
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_honey_pancakes_direct')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '2x #forge:dusts/sugar', 'minecraft:sweet_berries')
        .itemOutputs('12x rusticdelight:honey_pancake')
        .inputFluids('minecraft:milk 250', 'create:honey 250')
        .circuit(24)
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chocolate_pancakes')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', 'minecraft:cocoa_beans')
        .itemOutputs('2x rusticdelight:chocolate_pancakes')
        .inputFluids('minecraft:milk 375', 'create:chocolate 500')
        .circuit(1)
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chocolate_pancakes_direct')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', 'minecraft:cocoa_beans')
        .itemOutputs('12x rusticdelight:chocolate_pancake')
        .inputFluids('minecraft:milk 375', 'create:chocolate 500')
        .circuit(24)
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cherry_blossom_pancakes')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '#forge:dusts/sugar', '4x #rusticdelight:cherry_blossom_ingredients')
        .itemOutputs('2x rusticdelight:cherry_blossom_pancakes')
        .inputFluids('minecraft:milk 375')
        .circuit(1)
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cherry_blossom_pancakes_direct')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '#forge:dusts/sugar', '4x #rusticdelight:cherry_blossom_ingredients')
        .itemOutputs('12x rusticdelight:cherry_blossom_pancake')
        .inputFluids('minecraft:milk 375')
        .circuit(24)
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_vegetable_pancakes')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '2x #forge:crops/cabbage', '2x #forge:vegetables')
        .itemOutputs('2x rusticdelight:vegetable_pancakes')
        .inputFluids('minecraft:milk 375')
        .circuit(1)
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_vegetable_pancakes_direct')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '2x #forge:crops/cabbage', '2x #forge:vegetables')
        .itemOutputs('12x rusticdelight:vegetable_pancake')
        .inputFluids('minecraft:milk 375')
        .circuit(24)
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pumpkin_pancakes')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '#forge:dusts/sugar', 'minecraft:pumpkin')
        .itemOutputs('2x rusticdelight:pumpkin_pancakes')
        .inputFluids('minecraft:milk 250')
        .circuit(1)
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pumpkin_pancakes_direct')
        .itemInputs('3x #forge:grain', '2x #forge:eggs', '#forge:dusts/sugar', 'minecraft:pumpkin')
        .itemOutputs('12x rusticdelight:pumpkin_pancake')
        .inputFluids('minecraft:milk 250')
        .circuit(24)
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_potato_salad')
        .itemInputs('minecraft:potato', '#forge:eggs', '#forge:crops/onion')
        .itemOutputs('2x rusticdelight:potato_salad')
        .inputFluids('minecraft:milk 250')
        .circuit(3)
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_sweet_salad')
        .itemInputs('3x #forge:berries', '#forge:vegetables', '#forge:crops/cabbage')
        .itemOutputs('2x rusticdelight:sweet_salad')
        .inputFluids('create:honey 250')
        .circuit(3)
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_paprika_green')
        .itemInputs('4x rusticdelight:bell_pepper_green', '#forge:crops/rice', '#farmersdelight:cabbage_roll_ingredients')
        .itemOutputs('4x rusticdelight:stuffed_bell_pepper_green')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_paprika_yellow')
        .itemInputs('4x rusticdelight:bell_pepper_yellow', '#forge:crops/rice', '#farmersdelight:cabbage_roll_ingredients')
        .itemOutputs('4x rusticdelight:stuffed_bell_pepper_yellow')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_paprika_red')
        .itemInputs('4x rusticdelight:bell_pepper_red', '#forge:crops/rice', '#farmersdelight:cabbage_roll_ingredients')
        .itemOutputs('4x rusticdelight:stuffed_bell_pepper_red')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fried_dumplings_rd')
        .itemInputs('4x farmersdelight:dumplings', '6x #rusticdelight:cooking_oil_ingredients')
        .itemOutputs('4x rusticdelight:fried_dumplings')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_spring_rolls')
        .itemInputs('3x #forge:grain', '2x #forge:crops/cabbage', '#farmersdelight:cabbage_roll_ingredients', '6x #rusticdelight:cooking_oil_ingredients')
        .itemOutputs('4x rusticdelight:spring_rolls')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_paprika_roll_green')
        .itemInputs('rusticdelight:bell_pepper_green', '3x #forge:crops/rice')
        .itemOutputs('4x rusticdelight:bell_pepper_roll_green')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_paprika_roll_yellow')
        .itemInputs('rusticdelight:bell_pepper_yellow', '3x #forge:crops/rice')
        .itemOutputs('4x rusticdelight:bell_pepper_roll_yellow')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_paprika_roll_red')
        .itemInputs('rusticdelight:bell_pepper_red', '3x #forge:crops/rice')
        .itemOutputs('4x rusticdelight:bell_pepper_roll_red')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_calamari_roll')
        .itemInputs('rusticdelight:calamari', '3x #forge:crops/rice')
        .itemOutputs('4x rusticdelight:calamari_roll')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cherry_blossom_roll')
        .itemInputs('2x #rusticdelight:cherry_blossom_ingredients', '3x #forge:crops/rice')
        .itemOutputs('4x rusticdelight:cherry_blossom_roll')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_paprika_soup')
        .itemInputs('4x #forge:crops/bell_pepper')
        .inputFluids('minecraft:water 250')
        .itemOutputs('rusticdelight:bell_pepper_soup')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_paprika_pasta')
        .itemInputs('4x #forge:grain', 'rusticdelight:bell_pepper_green', 'rusticdelight:bell_pepper_yellow', 'rusticdelight:bell_pepper_red')
        .itemOutputs('rusticdelight:bell_pepper_pasta')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fried_calamari')
        .itemInputs('4x #rusticdelight:cooking_oil_ingredients', '#forge:raw_fishes/calamari', '#forge:crops/tomato', '2x #forge:grain', '#forge:eggs')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('rusticdelight:fried_calamari')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fried_chicken_rd')
        .itemInputs('4x #rusticdelight:cooking_oil_ingredients', '#forge:raw_chicken', '#forge:crops/onion', '2x #forge:grain', '#forge:eggs')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('rusticdelight:fried_chicken')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fried_mushrooms')
        .itemInputs('4x #rusticdelight:cooking_oil_ingredients', '2x #forge:mushrooms', '#forge:crops/onion')
        .itemOutputs('rusticdelight:fried_mushrooms')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_coffee_braised_beef')
        .itemInputs('#rusticdelight:coffee_food_ingredients', '#forge:raw_beef', '2x #forge:vegetables/potato', '2x minecraft:carrot')
        .itemOutputs('2x rusticdelight:fried_mushrooms')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_rice_roll_royale')
        .itemInputs('8x #forge:crops/rice', '3x #forge:crops/bell_pepper', '#forge:raw_fishes/calamari', '#rusticdelight:cherry_blossom_ingredients', '2x minecraft:dried_kelp')
        .itemOutputs('2x rusticdelight:rice_roll_royale')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    // Nether's delight foods
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_grilled_strider')
        .itemInputs('#nethersdelight:raw_strider', '#chipped:warped_roots', '#chipped:crimson_roots', '#chipped:warped_fungus', '#chipped:crimson_fungus')
        .itemOutputs('2x nethersdelight:grilled_strider')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_warped_moldy_meat')
        .itemInputs('nethersdelight:hoglin_loin', '2x #chipped:warped_roots')
        .itemOutputs('3x nethersdelight:warped_moldy_meat')
        .duration(560)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_strider_moss_stew')
        .itemInputs('#nethersdelight:raw_strider', '#chipped:crimson_roots', '2x #chipped:warped_fungus', '#chipped:crimson_fungus')
        .itemOutputs('2x nethersdelight:strider_moss_stew')
        .inputFluids('minecraft:lava 250')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_nether_skewer')
        .itemInputs('3x #forge:rods/blaze', '#nethersdelight:raw_strider', 'nethersdelight:propelpearl')
        .itemOutputs('3x nethersdelight:nether_skewer')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_magma_gelatin')
        .itemInputs('3x minecraft:magma_cream', 'nethersdelight:propelpearl')
        .itemOutputs('2x nethersdelight:magma_gelatin')
        .inputFluids('minecraft:lava 250')
        .duration(240)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_hoglin')
        .itemInputs('2x nethersdelight:hoglin_loin', '3x #chipped:warped_fungus', '3x #chipped:crimson_fungus', '#chipped:warped_roots', '#chipped:crimson_roots', 'nethersdelight:hoglin_hide')
        .itemOutputs('nethersdelight:stuffed_hoglin')
        .duration(3600)
        .EUt(GTValues.VA[GTValues.EV])
    // Ocean's delight foods
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_squid_rings')
        .itemInputs('oceansdelight:tentacles', '2x #forge:grain')
        .itemOutputs('4x oceansdelight:squid_rings')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_guardian_soup')
        .itemInputs('oceansdelight:guardian', '2x #forge:eggs', '2x #forge:crops/tomato', '#forge:crops/onion')
        .itemOutputs('2x oceansdelight:guardian_soup')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_elder_guardian_roll')
        .itemInputs('2x oceansdelight:elder_guardian_slice', '3x #forge:crops/rice')
        .itemOutputs('4x oceansdelight:elder_guardian_roll')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_wrapped_elder_guardian')
        .itemInputs('oceansdelight:elder_guardian_slice', '#forge:crops/tomato', '#forge:crops/cabbage', '#forge:crops/onion')
        .itemOutputs('2x oceansdelight:cabbage_wrapped_elder_guardian')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fugu_roll')
        .itemInputs('minecraft:pufferfish', '3x #forge:crops/rice')
        .itemOutputs('4x oceansdelight:fugu_roll')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_braised_sea_pickle')
        .itemInputs('minecraft:sea_pickle', '#forge:mushrooms')
        .itemOutputs('oceansdelight:braised_sea_pickle')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cooked_stuffed_cod')
        .itemInputs('2x #forge:raw_fishes/cod', '#forge:mushrooms', '#forge:crops/tomato', '#forge:crops/onion', 'minecraft:kelp')
        .itemOutputs('2x oceansdelight:cooked_stuffed_cod')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_honey_fried_kelp')
        .itemInputs('2x minecraft:dried_kelp')
        .inputFluids('create:honey 250')
        .itemOutputs('2x oceansdelight:honey_fried_kelp')
        .duration(420)
        .EUt(GTValues.VA[GTValues.EV])
    // End's delight foods
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_sauce')
        .itemInputs('minecraft:chorus_fruit', 'ends_delight:chorus_succulent')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x ends_delight:chorus_sauce')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_shulker_omelette')
        .itemInputs('ends_delight:shulker_meat', '2x #forge:eggs', '2x #forge:crops/onion')
        .itemOutputs('2x ends_delight:shulker_omelette')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_ender_sausage')
        .itemInputs('ends_delight:dragon_leg', '3x ends_delight:enderman_gristle', '2x ends_delight:chorus_sauce')
        .itemOutputs('8x ends_delight:ender_sausage')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_ender_bamboo_rice')
        .itemInputs('ends_delight:dragon_leg', '4x #forge:crops/rice', '4x minecraft:bamboo', '8x #forge:vegetables', '4x ends_delight:chorus_succulent')
        .itemOutputs('8x ends_delight:ender_bamboo_rice')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_rice_cake')
        .itemInputs('minecraft:chorus_fruit', '3x #forge:crops/rice', '2x #forge:dusts/sugar')
        .itemOutputs('3x ends_delight:stuffed_rice_cake')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_flower_pie')
        .itemInputs('4x #forge:grain', 'minecraft:chorus_flower', '2x #forge:dusts/sugar', '2x #minecraft:flowers')
        .itemOutputs('2x ends_delight:chorus_flower_pie')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_cookie')
        .itemInputs('3x #forge:grain', '2x minecraft:chorus_fruit')
        .itemOutputs('16x ends_delight:chorus_cookie')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_fruit_popsicle')
        .itemInputs('2x #forge:dusts/ice', '3x minecraft:chorus_fruit')
        .itemOutputs('3x ends_delight:chorus_fruit_popsicle')
        .inputFluids('minecraft:water 500')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_fruit_milk_tea')
        .itemInputs('minecraft:chorus_fruit')
        .itemOutputs('2x ends_delight:chorus_fruit_milk_tea')
        .inputFluids('minecraft:milk 250')
        .circuit(1)
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_bubble_tea')
        .itemInputs('minecraft:chorus_fruit', 'minecraft:ender_pearl')
        .itemOutputs('4x ends_delight:bubble_tea')
        .inputFluids('minecraft:milk 500')
        .circuit(2)
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_fruit_wine')
        .itemInputs('minecraft:chorus_fruit', '#forge:dusts/sugar')
        .itemOutputs('2x ends_delight:chorus_fruit_wine')
        .inputFluids('minecraft:water 250')
        .circuit(3)
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_flower_tea')
        .itemInputs('minecraft:chorus_flower', '2x minecraft:ghast_tear')
        .itemOutputs('4x ends_delight:chorus_flower_tea')
        .inputFluids('minecraft:water 500')
        .duration(360)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_fruit_pie')
        .itemInputs('4x #forge:grain', '#forge:dusts/sugar', '#minecraft:flowers', 'minecraft:chorus_fruit', 'minecraft:chorus_flower')
        .itemOutputs('2x ends_delight:chorus_fruit_pie')
        .inputFluids('minecraft:milk 250')
        .duration(480)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chorus_fruit_pie_slice')
        .itemInputs('4x #forge:grain', '#forge:dusts/sugar', '#minecraft:flowers', 'minecraft:chorus_fruit', 'minecraft:chorus_flower')
        .itemOutputs('8x ends_delight:chorus_fruit_pie_slice')
        .inputFluids('minecraft:milk 250')
        .duration(600)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_ender_congee')
        .itemInputs('4x #forge:crops/rice', 'minecraft:ender_pearl', 'ends_delight:raw_ender_mite_meat')
        .itemOutputs('4x ends_delight:ender_congee')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dragon_breath_and_chorus_soup')
        .itemInputs('2x #forge:mushrooms', '#minecraft:flowers', 'minecraft:dragon_breath', 'minecraft:chorus_flower', '2x minecraft:chorus_fruit')
        .inputFluids('minecraft:water 500')
        .itemOutputs('3x ends_delight:dragon_breath_and_chorus_soup')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_shulker_soup')
        .itemInputs('#forge:shulker_meat', 'minecraft:chorus_flower', 'ends_delight:chorus_succulent')
        .itemOutputs('2x ends_delight:shulker_soup')
        .inputFluids('minecraft:water 250')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_ender_noodle')
        .itemInputs('#forge:shulker_meat', 'ends_delight:raw_ender_mite_meat', 'ends_delight:chorus_sauce', '3x #forge:grain', '#forge:mushrooms')
        .itemOutputs('2x ends_delight:ender_noodle')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_enderman_gristle_stew')
        .itemInputs('3x ends_delight:enderman_gristle', 'minecraft:chorus_flower', 'ends_delight:chorus_succulent')
        .itemOutputs('2x ends_delight:enderman_gristle_stew')
        .inputFluids('minecraft:water 250')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stir_fried_shulker_meat')
        .itemInputs('#forge:shulker_meat', 'minecraft:chorus_fruit', '#forge:crops/tomato', '#forge:crops/onion')
        .itemOutputs('2x ends_delight:stir_fried_shulker_meat')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_roasted_dragon_steak')
        .itemInputs('ends_delight:dragon_leg', '2x ends_delight:chorus_sauce', '4x #forge:mushrooms', 'minecraft:chorus_fruit', '#forge:crops/tomato')
        .itemOutputs('4x ends_delight:roasted_dragon_steak')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_end_mixed_salad')
        .itemInputs('2x ends_delight:chorus_succulent', 'minecraft:chorus_fruit', '#forge:crops/tomato', '#forge:crops/cabbage')
        .itemOutputs('2x ends_delight:end_mixed_salad')
        .duration(480)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_assorted_salad')
        .itemInputs('ends_delight:chorus_succulent', 'minecraft:chorus_fruit', '#forge:crops/tomato', '#forge:crops/cabbage', '2x #forge:mushrooms')
        .itemOutputs('2x ends_delight:assorted_salad')
        .duration(480)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_end_barbecue_stick')
        .itemInputs('ends_delight:dragon_leg', '3x minecraft:chorus_fruit', '2x #forge:shulker_meat', '2x #forge:raw_ender_mite_meat')
        .itemOutputs('8x ends_delight:end_barbecue_stick')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dragon_leg_with_sauce_block')
        .itemInputs('ends_delight:dragon_leg', 'ends_delight:chorus_sauce', '2x #forge:crops/tomato', '3x #forge:mushrooms')
        .itemOutputs('ends_delight:dragon_leg_with_sauce_block')
        .duration(2400)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dragon_leg_with_sauce')
        .itemInputs('ends_delight:dragon_leg', 'ends_delight:chorus_sauce', '2x #forge:crops/tomato', '3x #forge:mushrooms')
        .itemOutputs('6x ends_delight:dragon_leg_with_sauce', '6x minecraft:bone_meal')
        .duration(2400)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_steamed_dragon_egg_block')
        .itemInputs('ends_delight:liquid_dragon_egg', '#forge:shulker_meat', 'minecraft:chorus_fruit', 'ends_delight:chorus_succulent', '#forge:mushrooms', '#forge:crops/onion')
        .itemOutputs('2x ends_delight:steamed_dragon_egg_block')
        .duration(1200)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_steamed_dragon_egg')
        .itemInputs('ends_delight:liquid_dragon_egg', '#forge:shulker_meat', 'minecraft:chorus_fruit', 'ends_delight:chorus_succulent', '#forge:mushrooms', '#forge:crops/onion')
        .itemOutputs('8x ends_delight:steamed_dragon_egg', 'ends_delight:half_dragon_egg_shell')
        .duration(1200)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dragon_meat_stew_block')
        .itemInputs('ends_delight:dragon_leg', '3x ends_delight:half_dragon_egg_shell', 'minecraft:chorus_fruit', 'ends_delight:chorus_succulent', '2x #forge:vegetables', '#forge:crops/tomato')
        .itemOutputs('3x ends_delight:dragon_meat_stew_block')
        .inputFluids('minecraft:water 250')
        .duration(1600)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dragon_meat_stew')
        .itemInputs('ends_delight:dragon_leg', 'minecraft:chorus_fruit', 'ends_delight:chorus_succulent', '2x #forge:vegetables', '#forge:crops/tomato')
        .itemOutputs('12x ends_delight:dragon_meat_stew')
        .inputFluids('minecraft:water 250')
        .duration(1600)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_grilled_shulker_block')
        .itemInputs('#forge:shulker_meat', 'minecraft:shulker_shell', 'minecraft:chorus_fruit', '2x ends_delight:chorus_succulent', '#forge:crops/tomato', '#forge:crops/onion')
        .itemOutputs('ends_delight:grilled_shulker_block')
        .duration(1200)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_grilled_shulker')
        .itemInputs('#forge:shulker_meat', 'minecraft:chorus_fruit', '2x ends_delight:chorus_succulent', '#forge:crops/tomato', '#forge:crops/onion')
        .itemOutputs('4x ends_delight:grilled_shulker')
        .duration(1200)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    // Brewery foods
    // Pork Knuckle
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pork_knuckle')
        .itemInputs('2x #forge:raw_pork', '#brewery:beer')
        .itemOutputs('2x brewery:pork_knuckle')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fried_chicken_fc')
        .itemInputs('3x #forge:raw_chicken', '2x #forge:crops/tomato', '#forge:grain')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('4x brewery:fried_chicken')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dumplings_bw')
        .itemInputs('2x #forge:crops/potato', 'farm_and_charm:lettuce')
        .itemOutputs('4x brewery:dumplings')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_sausage')
        .itemInputs('2x #forge:raw_beef', 'farm_and_charm:lettuce')
        .itemOutputs('3x brewery:sausage')
        .duration(900)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pretzel')
        .itemInputs('2x #forge:dusts/sugar', '3x #forge:grain')
        .inputFluids('minecraft:water 125', 'minecraft:milk 125')
        .itemOutputs('8x brewery:pretzel')
        .duration(600)
        .circuit(4)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_gingerbread')
        .itemInputs('2x #forge:dusts/sugar', '3x #forge:grain')
        .inputFluids('minecraft:water 125', 'minecraft:milk 125')
        .itemOutputs('8x brewery:gingerbread')
        .duration(600)
        .circuit(5)
        .EUt(GTValues.VA[GTValues.EV])

    // Farm and Charm foods
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_yeast')
        .itemInputs('#forge:dusts/sugar', '#forge:grain')
        .inputFluids('minecraft:water 125')
        .itemOutputs('16x farm_and_charm:yeast')
        .duration(1200)
        .circuit(26)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_farmer_salad')
        .itemInputs('farm_and_charm:lettuce', 'farm_and_charm:strawberry', '#forge:crops/tomato', '#forge:crops/onion')
        .itemOutputs('2x farm_and_charm:farmer_salad')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_oatmeal_with_strawberries')
        .itemInputs('farm_and_charm:oat', 'farm_and_charm:strawberry')
        .inputFluids('minecraft:milk 125')
        .itemOutputs('2x farm_and_charm:oatmeal_with_strawberries')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_simple_tomato_soup')
        .itemInputs('2x #forge:crops/tomato', 'minecraft:sugar')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:simple_tomato_soup')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_barley_soup')
        .itemInputs('2x farm_and_charm:barley', '#forge:eggs')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:barley_soup')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_onion_soup')
        .itemInputs('2x #forge:crops/onion', '#forge:grain')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:onion_soup')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_potato_soup')
        .itemInputs('#forge:crops/onion', '#forge:crops/potato')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:potato_soup')
        .duration(600)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_goulash')
        .itemInputs('#forge:raw_beef', '#forge:crops/onion', '#forge:crops/potato', '2x #forge:crops/tomato', '#forge:crops/carrot')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:goulash')
        .duration(720)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_pasta_with_onion_sauce')
        .itemInputs('3x #forge:grain', '2x #forge:crops/onion')
        .itemOutputs('2x farm_and_charm:pasta_with_onion_sauce')
        .duration(840)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_corn_grits')
        .itemInputs('#forge:grain', '2x #farm_and_charm:corn')
        .itemOutputs('3x farm_and_charm:corn_grits')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_barley_patties_with_potatoes')
        .itemInputs('2x farm_and_charm:barley', '#forge:eggs', 'farm_and_charm:lettuce', 'minecraft:potato')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('2x farm_and_charm:barley_patties_with_potatoes')
        .duration(840)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_beef_patty_with_vegetables')
        .itemInputs('#forge:raw_beef', 'minecraft:carrot', 'farm_and_charm:lettuce', 'minecraft:potato', 'minecraft:beetroot')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('2x farm_and_charm:beef_patty_with_vegetables')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_sausage_with_oat_patty')
        .itemInputs('#forge:raw_beef', 'minecraft:carrot', '2x farm_and_charm:oat', 'minecraft:potato')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('3x farm_and_charm:sausage_with_oat_patty')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_roasted_chicken')
        .itemInputs('#forge:raw_chicken', '2x #forge:grain', 'minecraft:carrot')
        .itemOutputs('3x farm_and_charm:roasted_chicken')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_roasted_corn')
        .itemInputs('2x farm_and_charm:corn')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('4x farm_and_charm:roasted_corn')
        .circuit(6)
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cooked_salmon')
        .itemInputs('#forge:raw_fishes/salmon', 'farm_and_charm:corn', 'farm_and_charm:lettuce')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('2x farm_and_charm:cooked_salmon')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cooked_cod')
        .itemInputs('#forge:raw_fishes/cod', 'minecraft:carrot', 'farm_and_charm:lettuce')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('2x farm_and_charm:cooked_cod')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chicken_wrapped_in_bacon')
        .itemInputs('#forge:raw_chicken', '#forge:raw_pork', '3x #forge:grain')
        .inputFluids('minecraft:milk 125')
        .itemOutputs('3x farm_and_charm:chicken_wrapped_in_bacon')
        .duration(1240)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_lamb_with_corn')
        .itemInputs('#forge:raw_mutton', 'farm_and_charm:corn', '2x minecraft:carrot')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('2x farm_and_charm:lamb_with_corn')
        .duration(1080)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_bacon_with_eggs')
        .itemInputs('#forge:raw_pork', '2x #forge:eggs')
        .inputFluids('minecraft:milk 125')
        .itemOutputs('2x farm_and_charm:bacon_with_eggs')
        .duration(1080)
        .circuit(1)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_oat_pancake')
        .itemInputs('3x farm_and_charm:oat', 'farm_and_charm:strawberry', '#forge:grain')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('6x farm_and_charm:oat_pancake')
        .duration(720)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_farmers_breakgast')
        .itemInputs('#forge:raw_pork', '#forge:eggs', '2x farm_and_charm:corn', '#forge:grain')
        .inputFluids('minecraft:milk 250')
        .itemOutputs('farm_and_charm:farmers_breakfast')
        .duration(1440)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_baked_lamb_ham')
        .itemInputs('#forge:raw_mutton', 'farm_and_charm:lettuce')
        .itemOutputs('2x farm_and_charm:baked_lamb_ham')
        .duration(1080)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_potato_with_roast_meat')
        .itemInputs('#forge:foods/meat/raw', 'minecraft:potato')
        .inputFluids('create:honey 125')
        .itemOutputs('2x farm_and_charm:potato_with_roast_meat')
        .duration(1080)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_chicken')
        .itemInputs('#forge:raw_chicken', '#forge:crops/onion', 'minecraft:carrot')
        .itemOutputs('2x farm_and_charm:stuffed_chicken')
        .duration(1080)
        .circuit(3)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_stuffed_rabbit')
        .itemInputs('minecraft:rabbit', '#forge:crops/onion', 'minecraft:carrot')
        .itemOutputs('2x farm_and_charm:stuffed_rabbit')
        .duration(1080)
        .circuit(3)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_grandmothers_strawberry_cake')
        .itemInputs('3x #forge:grain', '2x farm_and_charm:strawberry', '2x #forge:dusts/sugar')
        .itemOutputs('3x farm_and_charm:grandmothers_strawberry_cake')
        .duration(900)
        .circuit(2)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_strawberry_tea')
        .itemInputs('2x farm_and_charm:strawberry')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:strawberry_tea')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_nettle_tea')
        .itemInputs('2x farm_and_charm:wild_nettle')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:nettle_tea')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_ribwort_tea')
        .itemInputs('2x farm_and_charm:wild_ribwort')
        .inputFluids('minecraft:water 250')
        .itemOutputs('2x farm_and_charm:ribwort_tea')
        .duration(480)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cat_food')
        .itemInputs('#forge:raw_chicken', '#forge:raw_beef', '#forge:raw_pork', '#forge:raw_fishes')
        .itemOutputs('12x farm_and_charm:cat_food')
        .duration(720)
        .circuit(27)
        .EUt(GTValues.VA[GTValues.EV])   
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_dog_food_fc')
        .itemInputs('minecraft:bone', '2x #forge:raw_beef')
        .itemOutputs('8x farm_and_charm:dog_food')
        .duration(720)
        .circuit(27)
        .EUt(GTValues.VA[GTValues.EV])   
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_chicken_feed')
        .itemInputs('2x #c:wheat', '2x minecraft:carrot', '2x #forge:seeds')
        .itemOutputs('6x farm_and_charm:chicken_feed')
        .duration(360)
        .circuit(27)
        .EUt(GTValues.VA[GTValues.EV])   
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_horse_fodder')
        .itemInputs('3x #c:wheat', '2x minecraft:apple', 'minecraft:carrot')
        .itemOutputs('2x farm_and_charm:horse_fodder')
        .duration(600)
        .circuit(27)
        .EUt(GTValues.VA[GTValues.EV])   
    // Misc foods
    // EnderIO: Enderios
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_enderios')
        .itemInputs('#forge:grain', '#forge:dusts/ender_pearl')
        .inputFluids('minecraft:milk 125')
        .itemOutputs('2x enderio:enderios')
        .duration(540)
        .EUt(GTValues.VA[GTValues.EV])
    // InF Fire Stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_fire_stew')
        .itemInputs('#forge:rods/blaze', '2x iceandfire:fire_lily')
        .itemOutputs('2x iceandfire:fire_stew')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    // InF Frost Stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_frost_stew')
        .itemInputs('#forge:gems/prismarine', '2x iceandfire:frost_lily')
        .itemOutputs('2x iceandfire:frost_stew')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    // InF Lightning Stew
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_lightning_stew')
        .itemInputs('minecraft:chorus_fruit', '2x iceandfire:lightning_lily')
        .itemOutputs('2x iceandfire:lightning_stew')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    // GTCEU Purple Drink
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_purple_drink')
        .itemInputs('#forge:dusts/fluix', '#forge:dusts/gallium_arsenide', '#forge:dusts/paper')
        .inputFluids('gtceu:chloroform 250')
        .itemOutputs('6x gtceu:purple_drink')
        .duration(600)
        .EUt(GTValues.VA[GTValues.EV])
    // KJS Cockless pizza
    event.recipes.gtceu.advanced_culinary_array('kubejs:culinary_array_cockless_pizza')
        .itemInputs("2x #forge:rods", "6x #forge:grain", "3x #forge:crops/tomato", "#forge:eggs")
        .inputFluids('minecraft:milk 125')
        .itemOutputs('4x kubejs:dodo_pizza')
        .circuit(16)
        .EUt(GTValues.VA[GTValues.EV])
})
